- hosts: all
  roles:
    - geerlingguy.ntp
    - geerlingguy.security
    - geerlingguy.certbot
    - bee
    # TODO: make this only on the one actual website proxy server
    - srobo-nginx

  vars:
    # certbot_testmode: true # TODO: template this for local dev!
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: --quiet --no-self-upgrade --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"
    certbot_admin_email: infrastructure-team@studentrobotics.org
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
    - nginx
    certbot_certs:
    - domains:
      # TODO: swap these out in development
      - srobo.org
      - studentrobotics.org
