---
- name: Install nginx
  apt:
    pkg: nginx
    update_cache: yes
    state: latest
    cache_valid_time: 86400

- name: Install ssl-cert (for TLS certificates in development)
  apt:
    pkg: ssl-cert
  when: not certbot_create_if_missing

- name: Copy our configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify:
    reload nginx

- name: Copy dhparam.txt
  copy:
    src: files/dhparam.txt
    dest: /etc/nginx/dhparam.txt
    mode: "0644"
  notify:
    reload nginx

- name: Test nginx configuration file is valid
  command: /usr/sbin/nginx -t -c /etc/nginx/nginx.conf

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
