---
- name: Install nginx
  apt:
    pkg: nginx
    update_cache: yes
    state: latest
    cache_valid_time: 86400

- name: Copy our configuration
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify:
    reload nginx

- name: Test nginx configuration file is valid
  command: /usr/sbin/nginx -t -c /etc/nginx/nginx.conf

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
