name: CI

on: [push, pull_request]

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('dev-requirements.txt') }}

      - name: Install dependencies
        run: ./scripts/setup.sh

      - name: Run linters
        run: ./scripts/lint.sh
