name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: dev-requirements.txt

      - name: Install dependencies
        run: ./scripts/setup.sh

      - name: Run linters
        run: ./scripts/lint.sh
